export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const ADDEVENTFAIL = "ADDEVENT_FAILED";
export const ADDEVENTSUCCESS= "ADD_EVENT_SUCESS";

export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAILED = "GET_EVENT_FAILED";

export const EVENTREGISTRATIONSUCCESS = "EVENT_REGISTRATION_SUCCESS";
export const EVENTREGISTRATIONFAILED = "EVENT_REGISTRATION_FAILED";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";